### ISSUE TITLE
Handling regional calculations

### ISSUE THREAD

**Issue by spencerkclark** [spencerkclark/aospy-db#1]
Currently regional calculations are grouped in a single Dataset.  This breaks slightly with the prevailing convention in `aospy` in which there is a "1 result to 1 file" sort of system.  There is nothing about this that is inherently hard to handle within the database (for instance we could just add another column for the Region in the Calc table and all region computations would have their own row, but point to the same file), but out of consistency I'm wondering if we should think more about how we do this.

Another question is should we create a separate table to store more metadata about the Regions themselves?  This would be similar to the way Vars are handled currently.

Regardless, this is something that is lacking from the current setup and needs to be implemented.

**Comment by spencerahill** [comment]
My motivations for putting regions together were (1) to avoid creating so many files, and (2) because the amount of data for each one is so small.  For (2), in comparison to a 90x144 array for a standard resolution GCM, a region average is a scalar per each unit time.

Also, I find it useful to be able to load a single file of regional data and be able to compare different regions.  Granted, that functionality could be maintained even if they were in separate files, if aospy aggregated those files into a single object (but that sounds like it could be a pain).

> Another question is should we create a separate table to store more metadata about the Regions themselves? This would be similar to the way Vars are handled currently.

Yes.  Among other things, I would like to use region-averaged surface pressure in order to compute the pressure levels of model-native coordinates in that region, c.f. https://github.com/spencerahill/aospy/issues/51.  This would facilitate accurate plotting of region averages against each other, as compared to using the reference levels (`pref`).

Besides this, which would require a little work, I would like for all of the other existing metadata for Regions to be saved: name, lat and lon bounds, etc.

**Comment by spencerkclark** [comment]
This is all good.  It shouldn't be a big deal to take care of this.

**Comment by spencerkclark** [comment]
Closed by #7
